version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    mem_limit: 256m
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./conf/nginx.conf:/etc/nginx/conf.d/my-nginx.conf

networks:
  default:
    name: proxy
    external: true
    
