version: '2'

services:
  nginx-proxy:
    volumes:
      - ./conf/vhost.d:/etc/nginx/vhost.d
      - ./conf/certs:/etc/nginx/certs
  proxy-companion: 
    image: sebastienheyd/self-signed-proxy-companion       
    container_name: proxy-companion
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf/certs:/etc/nginx/certs

  dev_mysql:
    image: mysql:5.7
    container_name: dev_mysql
    ports: 
      - 3306:3306
    volumes:
      - dev_mysql_data:/var/lib/mysql
      - "./conf/mysql:/docker-entrypoint-initdb.d"
      - "./conf/mysql/my.cnf:/etc/mysql/conf.d/my.cnf"
    expose: 
      - 3306
    restart: always
    command: "--innodb_use_native_aio=0 --explicit_defaults_for_timestamp"
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_pass
    mem_limit: 1g

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on: 
      - dev_mysql
    ports:
      - 8080:80
    environment:
      - PMA_HOST=dev_mysql
      - PMA_USER=root
      - PMA_PASSWORD=mysql_root_pass
      - PMA_PORT=3306
      - VIRTUAL_PORT=80
      - UPLOAD_LIMIT=300M

volumes:
  dev_mysql_data:
    external: true
